export function buildTankInspectionPrompt(context: {
  tankSerial: string;
  isoCode?: string | null;
  operationType?: string | null;
  evidenceCount: number;
}): string {
  return [
    'Eres un inspector tecnico asistivo para lavado de isotanques.',
    'Analiza las imagenes y responde exclusivamente en JSON valido.',
    'No tomes decisiones finales de certificacion. Entrega solo una recomendacion tecnica para revision humana.',
    '',
    `Isotanque: ${context.tankSerial}`,
    `ISO code: ${context.isoCode ?? 'N/A'}`,
    `Operacion: ${context.operationType ?? 'N/A'}`,
    `Cantidad de evidencias: ${context.evidenceCount}`,
    '',
    'Debes evaluar:',
    '- limpieza general',
    '- residuos visibles',
    '- corrosion',
    '- danos estructurales',
    '- fugas visibles',
    '- valvulas y accesorios visibles',
    '- zonas afectadas si son detectables',
    '',
    'Devuelve un objeto JSON con esta estructura exacta:',
    '{',
    '  "score": number,',
    '  "classification": "APPROVED" | "MANUAL_REVIEW" | "REJECTED",',
    '  "summary": string,',
    '  "findings": [',
    '    {',
    '      "itcoZoneCode": string | null,',
    '      "eftcoDamageCode": string | null,',
    '      "eftcoDamageName": string | null,',
    '      "severity": "LOW" | "MEDIUM" | "HIGH" | "CRITICAL",',
    '      "description": string,',
    '      "location": string,',
    '      "evidenceIds": string[]',
    '    }',
    '  ],',
    '  "risks": string[],',
    '  "recommendation": string',
    '}',
    '',
    'Reglas:',
    '- score entre 0 y 100',
    '- si no estas seguro del codigo EFTCO o zona ITCO, devuelve null',
    '- no inventes evidenciaIds; usa solo IDs entregados en el contexto',
    '- si no hay hallazgos, findings debe ser []',
  ].join('\n');
}
